version: 2
jobs:
  build:
    docker:
      - image: surendrajat/twrp-builder:latest
    steps:
      - checkout
      - run:
          name: Initialize PBRP repo
          command: |
          repo init --depth=1 -u git://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-9.0
          repo sync
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build