version: 2
jobs:
  build:
    docker:
      # primary image
      - image: yshalsager/cyanogenmod:latest
      # secondary image
      - image: circleci/openjdk:8-jdk
    working_directory: /home/cmbuild/twrp
    steps:
      - checkout
      - run:
          name: AIO Build
          command: |
            DIR=$(pwd) && echo $DIR
            echo "Make Up2date"
            sudo apt-get -qqy update && sudo apt-get -qqy upgrade
            echo "Setup all the prerequisites"
            PATH=~/bin:$PATH
            curl --create-dirs -L -o ~/bin/repo -O -L https://github.com/akhilnarang/repo/raw/master/repo
            chmod a+x ~/bin/repo
            which repo
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            echo "Initialize & Sync PBRP repo"
            echo $(pwd)
            repo init --depth=1 -q -u git://github.com/PitchBlackRecoveryProject/manifest_pb.git -b PBRP
            time repo sync -c -f -q --force-sync --no-clone-bundle --no-tags -j32
            echo "Clean up the .repo, no use of it"
            rm -rf .repo
            echo "Source Files are Here now"
            ls -la .
            echo "Get the Device Tree on place"
            git clone https://github.com/PitchBlackRecoveryProject/android_device_LYF_mobee01a-pbrp -b PitchBlack device/LYF/mobee01a
            rm -rf bootable/recovery && git clone https://github.com/PitchBlackRecoveryProject/android_bootable_recovery -b android-9.0 bootable/recovery
            rm -rf vendor/pb && git clone https://github.com/PitchBlackRecoveryProject/vendor_pb -b pb vendor/pb
            set -ex
            echo "Start the Build Process"
            source build/envsetup.sh
            lunch omni_mobee01a-userdebug
            make -j16 recoveryimage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
